const demoData: JobInterface[] = [
  {
    employer_name: "Google",
    employer_logo: "https://github.com/ashutosh887.png",
    employer_website: "https://www.google.com",
    employer_company_type: "Technology",
    job_publisher: "LinkedIn",
    job_id: "12345",
    job_employment_type: "Full-Time",
    job_title: "Software Engineer",
    job_apply_link: "https://www.google.com/careers",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.8,
    apply_options: { option1: "Option 1", option2: "Option 2" },
    job_description: "Exciting job at Google...",
    job_is_remote: false,
    job_posted_at_timestamp: 1700490127,
    job_posted_at_datetime_utc: "2023-11-20T14:22:07.000Z",
    job_city: "Mountain View",
    job_state: "CA",
    job_country: "US",
    job_latitude: 37.7749,
    job_longitude: -122.4194,
    job_benefits: ["Health Insurance", "Stock Options"],
    job_google_link:
      "https://www.google.com/search?q=software+engineer+at+google",
    job_offer_expiration_datetime_utc: "2023-12-21T14:22:07.000Z",
    job_offer_expiration_timestamp: 1703168527,
    job_required_experience: ["3+ years of experience"],
    job_required_skills: ["JavaScript", "React"],
    job_required_education: ["Bachelor's Degree in Computer Science"],
    job_experience_in_place_of_education: false,
    job_min_salary: 90000,
    job_max_salary: 120000,
    job_salary_currency: "USD",
    job_salary_period: "Yearly",
    job_highlights: ["Flexible work hours", "Free snacks"],
    job_job_title: "Software Engineer",
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "Facebook",
    employer_logo: "https://github.com/ashutosh887.png",
    employer_website: "https://www.facebook.com",
    employer_company_type: "Social Media",
    job_publisher: "Glassdoor",
    job_id: "54321",
    job_employment_type: "Contractor",
    job_title: "Frontend Developer",
    job_apply_link: "https://www.facebook.com/careers",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.75,
    apply_options: { option1: "Apply Now", option2: "Submit Resume" },
    job_description: "Exciting job at Facebook...",
    job_is_remote: true,
    job_posted_at_timestamp: 1700490127,
    job_posted_at_datetime_utc: "2023-11-21T10:30:00.000Z",
    job_city: "Menlo Park",
    job_state: "CA",
    job_country: "US",
    job_latitude: 37.4529,
    job_longitude: -122.1817,
    job_benefits: ["Health Insurance", "Flexible Work Hours"],
    job_google_link:
      "https://www.google.com/search?q=frontend+developer+at+facebook",
    job_offer_expiration_datetime_utc: "2023-12-22T10:30:00.000Z",
    job_offer_expiration_timestamp: 1703254600,
    job_required_experience: ["5+ years of experience"],
    job_required_skills: ["React", "JavaScript", "HTML", "CSS"],
    job_required_education: ["Bachelor's Degree in Computer Science"],
    job_experience_in_place_of_education: false,
    job_min_salary: 120000,
    job_max_salary: 150000,
    job_salary_currency: "USD",
    job_salary_period: "Yearly",
    job_highlights: ["Remote Work", "401(k) Plan"],
    job_job_title: "Frontend Developer",
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "Amazon",
    employer_logo: "https://github.com/ashutosh887.png",
    employer_website: "https://www.amazon.com",
    employer_company_type: "E-commerce",
    job_publisher: "Indeed",
    job_id: "98765",
    job_employment_type: "Full-Time",
    job_title: "Data Scientist",
    job_apply_link: "https://www.amazon.jobs",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.9,
    apply_options: { option1: "Submit Application", option2: "Apply Now" },
    job_description: "Exciting job at Amazon...",
    job_is_remote: false,
    job_posted_at_timestamp: 1700490127,
    job_posted_at_datetime_utc: "2023-11-22T08:45:00.000Z",
    job_city: "Seattle",
    job_state: "WA",
    job_country: "US",
    job_latitude: 47.6062,
    job_longitude: -122.3321,
    job_benefits: ["Health Insurance", "Stock Options", "Tuition Assistance"],
    job_google_link: "https://www.google.com/search?q=data+scientist+at+amazon",
    job_offer_expiration_datetime_utc: "2023-12-23T08:45:00.000Z",
    job_offer_expiration_timestamp: 1703340700,
    job_required_experience: ["7+ years of experience"],
    job_required_skills: ["Machine Learning", "Python", "SQL"],
    job_required_education: ["Master's Degree in Data Science"],
    job_experience_in_place_of_education: false,
    job_min_salary: 130000,
    job_max_salary: 160000,
    job_salary_currency: "USD",
    job_salary_period: "Yearly",
    job_highlights: ["401(k) Matching", "Flexible Spending Account"],
    job_job_title: "Data Scientist",
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  // Add more entries as needed
];

export default demoData;
